trigger:
- main

pool:
  name: Default
  demands: 
    Unity_2019.4.16f1

steps:
- script: |
      echo $(Agent.WorkFolder) 

# copy original project library to binary directory to build (s)
# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Agent.WorkFolder)\unity\unity-cicd\Library'
#     contents: '**' # copies all files in the specified source folder and all files in all sub-folders
#     targetFolder: '$(Build.Repository.LocalPath)\Library'
#     overWrite: true # Optional
#     #cleanTargetFolder: false # Optional
#     #flattenFolders: false # Optional
#     #preserveTimestamp: false # Optional

# unity PC build
- task: UnityBuildTask@3
  inputs:
    buildTarget: 'WebGL'
    #unityProjectPath: '$(Agent.WorkFolder)\unity\unity-cicd'
    # outputPath: '$(Build.BinariesDirectory)'
    unityProjectPath: 'C:\Users\Administrator\projects\unity\unity-cicd'
    outputPath: 'C:\Users\Administrator\projects\unity-build'
    outputFileName: 'unity-cicd'

###

# # cleanup for unity build
# - task: DeleteFiles@1
#   inputs:
#     SourceFolder: '$(Build.ArtifactStagingDirectory)'
#     Contents: '**/*'
    
# # get the previously secured library (if any) for performance reasons
# - task: DeleteFiles@1
#   inputs:
#     SourceFolder: '$(Build.Repository.LocalPath)\Library' 
#     Contents: '**/*'
# - task: CmdLine@2
#   inputs:
#     script: 'if EXIST "$(Build.BinariesDirectory)\Library\" move "$(Build.BinariesDirectory)\Library" "$(Build.Repository.LocalPath)\Library"'


    
